local data = {
	[1] = { Id=1, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[2] = { Id=2, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[3] = { Id=3, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[4] = { Id=4, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[5] = { Id=5, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[6] = { Id=6, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[7] = { Id=7, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[8] = { Id=8, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[9] = { Id=9, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[10] = { Id=10, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[11] = { Id=11, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[12] = { Id=12, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[13] = { Id=13, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[14] = { Id=14, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[15] = { Id=15, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[16] = { Id=16, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[17] = { Id=17, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[18] = { Id=18, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[19] = { Id=19, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[20] = { Id=20, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[21] = { Id=21, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[22] = { Id=22, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[23] = { Id=23, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[24] = { Id=24, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[25] = { Id=25, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[26] = { Id=26, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[27] = { Id=27, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },
	[28] = { Id=28, Name="卡尔", ShopId=0, Avatar=2, Say="你好" },

}
return data
