-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "app.net.pb.protobuf"
module('proto.gs_main')


GS_MESSAGE = protobuf.Descriptor();
local GS_MESSAGE_S_MSG_NAME_FIELD = protobuf.FieldDescriptor();
local GS_MESSAGE_S_MSG_BODY_FIELD = protobuf.FieldDescriptor();
GS_REQUEST = protobuf.Descriptor();
local GS_REQUEST_U_PROTOCOL_ID_FIELD = protobuf.FieldDescriptor();
local GS_REQUEST_U_VALID_CODE_FIELD = protobuf.FieldDescriptor();
local GS_REQUEST_MESSAGE_FIELD = protobuf.FieldDescriptor();
GS_RESPONSE = protobuf.Descriptor();
local GS_RESPONSE_U_PROTOCOL_ID_FIELD = protobuf.FieldDescriptor();
local GS_RESPONSE_U_VALID_CODE_FIELD = protobuf.FieldDescriptor();
local GS_RESPONSE_U_TIME_FIELD = protobuf.FieldDescriptor();
local GS_RESPONSE_U_ERROR_CODE_FIELD = protobuf.FieldDescriptor();
local GS_RESPONSE_MESSAGE_FIELD = protobuf.FieldDescriptor();

GS_MESSAGE_S_MSG_NAME_FIELD.name = "s_msg_name"
GS_MESSAGE_S_MSG_NAME_FIELD.full_name = ".GS_Message.s_msg_name"
GS_MESSAGE_S_MSG_NAME_FIELD.number = 1
GS_MESSAGE_S_MSG_NAME_FIELD.index = 0
GS_MESSAGE_S_MSG_NAME_FIELD.label = 2
GS_MESSAGE_S_MSG_NAME_FIELD.has_default_value = false
GS_MESSAGE_S_MSG_NAME_FIELD.default_value = nil
GS_MESSAGE_S_MSG_NAME_FIELD.type = 9
GS_MESSAGE_S_MSG_NAME_FIELD.cpp_type = 9

GS_MESSAGE_S_MSG_BODY_FIELD.name = "s_msg_body"
GS_MESSAGE_S_MSG_BODY_FIELD.full_name = ".GS_Message.s_msg_body"
GS_MESSAGE_S_MSG_BODY_FIELD.number = 2
GS_MESSAGE_S_MSG_BODY_FIELD.index = 1
GS_MESSAGE_S_MSG_BODY_FIELD.label = 2
GS_MESSAGE_S_MSG_BODY_FIELD.has_default_value = false
GS_MESSAGE_S_MSG_BODY_FIELD.default_value = nil
GS_MESSAGE_S_MSG_BODY_FIELD.type = 12
GS_MESSAGE_S_MSG_BODY_FIELD.cpp_type = 9

GS_MESSAGE.name = "GS_Message"
GS_MESSAGE.full_name = ".GS_Message"
GS_MESSAGE.nested_types = {}
GS_MESSAGE.enum_types = {}
GS_MESSAGE.fields = {GS_MESSAGE_S_MSG_NAME_FIELD, GS_MESSAGE_S_MSG_BODY_FIELD}
GS_MESSAGE.is_extendable = false
GS_MESSAGE.extensions = {}
GS_REQUEST_U_PROTOCOL_ID_FIELD.name = "u_protocol_id"
GS_REQUEST_U_PROTOCOL_ID_FIELD.full_name = ".GS_Request.u_protocol_id"
GS_REQUEST_U_PROTOCOL_ID_FIELD.number = 1
GS_REQUEST_U_PROTOCOL_ID_FIELD.index = 0
GS_REQUEST_U_PROTOCOL_ID_FIELD.label = 2
GS_REQUEST_U_PROTOCOL_ID_FIELD.has_default_value = false
GS_REQUEST_U_PROTOCOL_ID_FIELD.default_value = nil
GS_REQUEST_U_PROTOCOL_ID_FIELD.type = 4
GS_REQUEST_U_PROTOCOL_ID_FIELD.cpp_type = 4

GS_REQUEST_U_VALID_CODE_FIELD.name = "u_valid_code"
GS_REQUEST_U_VALID_CODE_FIELD.full_name = ".GS_Request.u_valid_code"
GS_REQUEST_U_VALID_CODE_FIELD.number = 2
GS_REQUEST_U_VALID_CODE_FIELD.index = 1
GS_REQUEST_U_VALID_CODE_FIELD.label = 2
GS_REQUEST_U_VALID_CODE_FIELD.has_default_value = false
GS_REQUEST_U_VALID_CODE_FIELD.default_value = nil
GS_REQUEST_U_VALID_CODE_FIELD.type = 13
GS_REQUEST_U_VALID_CODE_FIELD.cpp_type = 3

GS_REQUEST_MESSAGE_FIELD.name = "message"
GS_REQUEST_MESSAGE_FIELD.full_name = ".GS_Request.message"
GS_REQUEST_MESSAGE_FIELD.number = 3
GS_REQUEST_MESSAGE_FIELD.index = 2
GS_REQUEST_MESSAGE_FIELD.label = 1
GS_REQUEST_MESSAGE_FIELD.has_default_value = false
GS_REQUEST_MESSAGE_FIELD.default_value = nil
GS_REQUEST_MESSAGE_FIELD.message_type = GS_MESSAGE
GS_REQUEST_MESSAGE_FIELD.type = 11
GS_REQUEST_MESSAGE_FIELD.cpp_type = 10

GS_REQUEST.name = "GS_Request"
GS_REQUEST.full_name = ".GS_Request"
GS_REQUEST.nested_types = {}
GS_REQUEST.enum_types = {}
GS_REQUEST.fields = {GS_REQUEST_U_PROTOCOL_ID_FIELD, GS_REQUEST_U_VALID_CODE_FIELD, GS_REQUEST_MESSAGE_FIELD}
GS_REQUEST.is_extendable = false
GS_REQUEST.extensions = {}
GS_RESPONSE_U_PROTOCOL_ID_FIELD.name = "u_protocol_id"
GS_RESPONSE_U_PROTOCOL_ID_FIELD.full_name = ".GS_Response.u_protocol_id"
GS_RESPONSE_U_PROTOCOL_ID_FIELD.number = 1
GS_RESPONSE_U_PROTOCOL_ID_FIELD.index = 0
GS_RESPONSE_U_PROTOCOL_ID_FIELD.label = 2
GS_RESPONSE_U_PROTOCOL_ID_FIELD.has_default_value = false
GS_RESPONSE_U_PROTOCOL_ID_FIELD.default_value = nil
GS_RESPONSE_U_PROTOCOL_ID_FIELD.type = 4
GS_RESPONSE_U_PROTOCOL_ID_FIELD.cpp_type = 4

GS_RESPONSE_U_VALID_CODE_FIELD.name = "u_valid_code"
GS_RESPONSE_U_VALID_CODE_FIELD.full_name = ".GS_Response.u_valid_code"
GS_RESPONSE_U_VALID_CODE_FIELD.number = 2
GS_RESPONSE_U_VALID_CODE_FIELD.index = 1
GS_RESPONSE_U_VALID_CODE_FIELD.label = 2
GS_RESPONSE_U_VALID_CODE_FIELD.has_default_value = false
GS_RESPONSE_U_VALID_CODE_FIELD.default_value = nil
GS_RESPONSE_U_VALID_CODE_FIELD.type = 13
GS_RESPONSE_U_VALID_CODE_FIELD.cpp_type = 3

GS_RESPONSE_U_TIME_FIELD.name = "u_time"
GS_RESPONSE_U_TIME_FIELD.full_name = ".GS_Response.u_time"
GS_RESPONSE_U_TIME_FIELD.number = 3
GS_RESPONSE_U_TIME_FIELD.index = 2
GS_RESPONSE_U_TIME_FIELD.label = 1
GS_RESPONSE_U_TIME_FIELD.has_default_value = false
GS_RESPONSE_U_TIME_FIELD.default_value = nil
GS_RESPONSE_U_TIME_FIELD.type = 13
GS_RESPONSE_U_TIME_FIELD.cpp_type = 3

GS_RESPONSE_U_ERROR_CODE_FIELD.name = "u_error_code"
GS_RESPONSE_U_ERROR_CODE_FIELD.full_name = ".GS_Response.u_error_code"
GS_RESPONSE_U_ERROR_CODE_FIELD.number = 4
GS_RESPONSE_U_ERROR_CODE_FIELD.index = 3
GS_RESPONSE_U_ERROR_CODE_FIELD.label = 1
GS_RESPONSE_U_ERROR_CODE_FIELD.has_default_value = false
GS_RESPONSE_U_ERROR_CODE_FIELD.default_value = nil
GS_RESPONSE_U_ERROR_CODE_FIELD.type = 13
GS_RESPONSE_U_ERROR_CODE_FIELD.cpp_type = 3

GS_RESPONSE_MESSAGE_FIELD.name = "message"
GS_RESPONSE_MESSAGE_FIELD.full_name = ".GS_Response.message"
GS_RESPONSE_MESSAGE_FIELD.number = 5
GS_RESPONSE_MESSAGE_FIELD.index = 4
GS_RESPONSE_MESSAGE_FIELD.label = 1
GS_RESPONSE_MESSAGE_FIELD.has_default_value = false
GS_RESPONSE_MESSAGE_FIELD.default_value = nil
GS_RESPONSE_MESSAGE_FIELD.message_type = GS_MESSAGE
GS_RESPONSE_MESSAGE_FIELD.type = 11
GS_RESPONSE_MESSAGE_FIELD.cpp_type = 10

GS_RESPONSE.name = "GS_Response"
GS_RESPONSE.full_name = ".GS_Response"
GS_RESPONSE.nested_types = {}
GS_RESPONSE.enum_types = {}
GS_RESPONSE.fields = {GS_RESPONSE_U_PROTOCOL_ID_FIELD, GS_RESPONSE_U_VALID_CODE_FIELD, GS_RESPONSE_U_TIME_FIELD, GS_RESPONSE_U_ERROR_CODE_FIELD, GS_RESPONSE_MESSAGE_FIELD}
GS_RESPONSE.is_extendable = false
GS_RESPONSE.extensions = {}

GS_Message = protobuf.Message(GS_MESSAGE)
GS_Request = protobuf.Message(GS_REQUEST)
GS_Response = protobuf.Message(GS_RESPONSE)

