-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "app.net.pb.protobuf"
module('proto.msg_level')


LVUPRESPONSE = protobuf.Descriptor();
local LVUPRESPONSE_U_STATUS_FIELD = protobuf.FieldDescriptor();

LVUPRESPONSE_U_STATUS_FIELD.name = "u_status"
LVUPRESPONSE_U_STATUS_FIELD.full_name = ".LvUpResponse.u_status"
LVUPRESPONSE_U_STATUS_FIELD.number = 1
LVUPRESPONSE_U_STATUS_FIELD.index = 0
LVUPRESPONSE_U_STATUS_FIELD.label = 2
LVUPRESPONSE_U_STATUS_FIELD.has_default_value = false
LVUPRESPONSE_U_STATUS_FIELD.default_value = nil
LVUPRESPONSE_U_STATUS_FIELD.type = 13
LVUPRESPONSE_U_STATUS_FIELD.cpp_type = 3

LVUPRESPONSE.name = "LvUpResponse"
LVUPRESPONSE.full_name = ".LvUpResponse"
LVUPRESPONSE.nested_types = {}
LVUPRESPONSE.enum_types = {}
LVUPRESPONSE.fields = {LVUPRESPONSE_U_STATUS_FIELD}
LVUPRESPONSE.is_extendable = false
LVUPRESPONSE.extensions = {}

LvUpResponse = protobuf.Message(LVUPRESPONSE)

