-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "app.net.pb.protobuf"
module('proto.msg_chat')


CHATREQUEST = protobuf.Descriptor();
local CHATREQUEST_S_CONTENT_FIELD = protobuf.FieldDescriptor();
local CHATREQUEST_U_CHANNELTYPE_FIELD = protobuf.FieldDescriptor();
CHATRESPONSE = protobuf.Descriptor();
local CHATRESPONSE_U_STATUS_FIELD = protobuf.FieldDescriptor();
CHATTOREQUEST = protobuf.Descriptor();
local CHATTOREQUEST_S_CONTENT_FIELD = protobuf.FieldDescriptor();
local CHATTOREQUEST_U_RECVER_ID_FIELD = protobuf.FieldDescriptor();
CHATTORESPONSE = protobuf.Descriptor();
local CHATTORESPONSE_U_STATUS_FIELD = protobuf.FieldDescriptor();

CHATREQUEST_S_CONTENT_FIELD.name = "s_content"
CHATREQUEST_S_CONTENT_FIELD.full_name = ".ChatRequest.s_content"
CHATREQUEST_S_CONTENT_FIELD.number = 1
CHATREQUEST_S_CONTENT_FIELD.index = 0
CHATREQUEST_S_CONTENT_FIELD.label = 2
CHATREQUEST_S_CONTENT_FIELD.has_default_value = false
CHATREQUEST_S_CONTENT_FIELD.default_value = nil
CHATREQUEST_S_CONTENT_FIELD.type = 9
CHATREQUEST_S_CONTENT_FIELD.cpp_type = 9

CHATREQUEST_U_CHANNELTYPE_FIELD.name = "u_channeltype"
CHATREQUEST_U_CHANNELTYPE_FIELD.full_name = ".ChatRequest.u_channeltype"
CHATREQUEST_U_CHANNELTYPE_FIELD.number = 2
CHATREQUEST_U_CHANNELTYPE_FIELD.index = 1
CHATREQUEST_U_CHANNELTYPE_FIELD.label = 2
CHATREQUEST_U_CHANNELTYPE_FIELD.has_default_value = false
CHATREQUEST_U_CHANNELTYPE_FIELD.default_value = nil
CHATREQUEST_U_CHANNELTYPE_FIELD.type = 13
CHATREQUEST_U_CHANNELTYPE_FIELD.cpp_type = 3

CHATREQUEST.name = "ChatRequest"
CHATREQUEST.full_name = ".ChatRequest"
CHATREQUEST.nested_types = {}
CHATREQUEST.enum_types = {}
CHATREQUEST.fields = {CHATREQUEST_S_CONTENT_FIELD, CHATREQUEST_U_CHANNELTYPE_FIELD}
CHATREQUEST.is_extendable = false
CHATREQUEST.extensions = {}
CHATRESPONSE_U_STATUS_FIELD.name = "u_status"
CHATRESPONSE_U_STATUS_FIELD.full_name = ".ChatResponse.u_status"
CHATRESPONSE_U_STATUS_FIELD.number = 1
CHATRESPONSE_U_STATUS_FIELD.index = 0
CHATRESPONSE_U_STATUS_FIELD.label = 2
CHATRESPONSE_U_STATUS_FIELD.has_default_value = false
CHATRESPONSE_U_STATUS_FIELD.default_value = nil
CHATRESPONSE_U_STATUS_FIELD.type = 13
CHATRESPONSE_U_STATUS_FIELD.cpp_type = 3

CHATRESPONSE.name = "ChatResponse"
CHATRESPONSE.full_name = ".ChatResponse"
CHATRESPONSE.nested_types = {}
CHATRESPONSE.enum_types = {}
CHATRESPONSE.fields = {CHATRESPONSE_U_STATUS_FIELD}
CHATRESPONSE.is_extendable = false
CHATRESPONSE.extensions = {}
CHATTOREQUEST_S_CONTENT_FIELD.name = "s_content"
CHATTOREQUEST_S_CONTENT_FIELD.full_name = ".ChatToRequest.s_content"
CHATTOREQUEST_S_CONTENT_FIELD.number = 1
CHATTOREQUEST_S_CONTENT_FIELD.index = 0
CHATTOREQUEST_S_CONTENT_FIELD.label = 2
CHATTOREQUEST_S_CONTENT_FIELD.has_default_value = false
CHATTOREQUEST_S_CONTENT_FIELD.default_value = nil
CHATTOREQUEST_S_CONTENT_FIELD.type = 9
CHATTOREQUEST_S_CONTENT_FIELD.cpp_type = 9

CHATTOREQUEST_U_RECVER_ID_FIELD.name = "u_recver_id"
CHATTOREQUEST_U_RECVER_ID_FIELD.full_name = ".ChatToRequest.u_recver_id"
CHATTOREQUEST_U_RECVER_ID_FIELD.number = 2
CHATTOREQUEST_U_RECVER_ID_FIELD.index = 1
CHATTOREQUEST_U_RECVER_ID_FIELD.label = 2
CHATTOREQUEST_U_RECVER_ID_FIELD.has_default_value = false
CHATTOREQUEST_U_RECVER_ID_FIELD.default_value = nil
CHATTOREQUEST_U_RECVER_ID_FIELD.type = 13
CHATTOREQUEST_U_RECVER_ID_FIELD.cpp_type = 3

CHATTOREQUEST.name = "ChatToRequest"
CHATTOREQUEST.full_name = ".ChatToRequest"
CHATTOREQUEST.nested_types = {}
CHATTOREQUEST.enum_types = {}
CHATTOREQUEST.fields = {CHATTOREQUEST_S_CONTENT_FIELD, CHATTOREQUEST_U_RECVER_ID_FIELD}
CHATTOREQUEST.is_extendable = false
CHATTOREQUEST.extensions = {}
CHATTORESPONSE_U_STATUS_FIELD.name = "u_status"
CHATTORESPONSE_U_STATUS_FIELD.full_name = ".ChatToResponse.u_status"
CHATTORESPONSE_U_STATUS_FIELD.number = 1
CHATTORESPONSE_U_STATUS_FIELD.index = 0
CHATTORESPONSE_U_STATUS_FIELD.label = 2
CHATTORESPONSE_U_STATUS_FIELD.has_default_value = false
CHATTORESPONSE_U_STATUS_FIELD.default_value = nil
CHATTORESPONSE_U_STATUS_FIELD.type = 13
CHATTORESPONSE_U_STATUS_FIELD.cpp_type = 3

CHATTORESPONSE.name = "ChatToResponse"
CHATTORESPONSE.full_name = ".ChatToResponse"
CHATTORESPONSE.nested_types = {}
CHATTORESPONSE.enum_types = {}
CHATTORESPONSE.fields = {CHATTORESPONSE_U_STATUS_FIELD}
CHATTORESPONSE.is_extendable = false
CHATTORESPONSE.extensions = {}

ChatRequest = protobuf.Message(CHATREQUEST)
ChatResponse = protobuf.Message(CHATRESPONSE)
ChatToRequest = protobuf.Message(CHATTOREQUEST)
ChatToResponse = protobuf.Message(CHATTORESPONSE)

