-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "app.net.pb.protobuf"
module('proto.msg_reg')


REGREQUEST = protobuf.Descriptor();
local REGREQUEST_S_USER_NAME_FIELD = protobuf.FieldDescriptor();
local REGREQUEST_S_USER_PASSWORD_FIELD = protobuf.FieldDescriptor();
REGRESPONSE = protobuf.Descriptor();
local REGRESPONSE_U_STATUS_FIELD = protobuf.FieldDescriptor();

REGREQUEST_S_USER_NAME_FIELD.name = "s_user_name"
REGREQUEST_S_USER_NAME_FIELD.full_name = ".RegRequest.s_user_name"
REGREQUEST_S_USER_NAME_FIELD.number = 1
REGREQUEST_S_USER_NAME_FIELD.index = 0
REGREQUEST_S_USER_NAME_FIELD.label = 2
REGREQUEST_S_USER_NAME_FIELD.has_default_value = false
REGREQUEST_S_USER_NAME_FIELD.default_value = nil
REGREQUEST_S_USER_NAME_FIELD.type = 9
REGREQUEST_S_USER_NAME_FIELD.cpp_type = 9

REGREQUEST_S_USER_PASSWORD_FIELD.name = "s_user_password"
REGREQUEST_S_USER_PASSWORD_FIELD.full_name = ".RegRequest.s_user_password"
REGREQUEST_S_USER_PASSWORD_FIELD.number = 2
REGREQUEST_S_USER_PASSWORD_FIELD.index = 1
REGREQUEST_S_USER_PASSWORD_FIELD.label = 2
REGREQUEST_S_USER_PASSWORD_FIELD.has_default_value = false
REGREQUEST_S_USER_PASSWORD_FIELD.default_value = nil
REGREQUEST_S_USER_PASSWORD_FIELD.type = 9
REGREQUEST_S_USER_PASSWORD_FIELD.cpp_type = 9

REGREQUEST.name = "RegRequest"
REGREQUEST.full_name = ".RegRequest"
REGREQUEST.nested_types = {}
REGREQUEST.enum_types = {}
REGREQUEST.fields = {REGREQUEST_S_USER_NAME_FIELD, REGREQUEST_S_USER_PASSWORD_FIELD}
REGREQUEST.is_extendable = false
REGREQUEST.extensions = {}
REGRESPONSE_U_STATUS_FIELD.name = "u_status"
REGRESPONSE_U_STATUS_FIELD.full_name = ".RegResponse.u_status"
REGRESPONSE_U_STATUS_FIELD.number = 1
REGRESPONSE_U_STATUS_FIELD.index = 0
REGRESPONSE_U_STATUS_FIELD.label = 2
REGRESPONSE_U_STATUS_FIELD.has_default_value = false
REGRESPONSE_U_STATUS_FIELD.default_value = nil
REGRESPONSE_U_STATUS_FIELD.type = 13
REGRESPONSE_U_STATUS_FIELD.cpp_type = 3

REGRESPONSE.name = "RegResponse"
REGRESPONSE.full_name = ".RegResponse"
REGRESPONSE.nested_types = {}
REGRESPONSE.enum_types = {}
REGRESPONSE.fields = {REGRESPONSE_U_STATUS_FIELD}
REGRESPONSE.is_extendable = false
REGRESPONSE.extensions = {}

RegRequest = protobuf.Message(REGREQUEST)
RegResponse = protobuf.Message(REGRESPONSE)

